import numpy as np
arr = np.array([[1]])
print(arr)
arr

In [ ]:
import numpy as np
arr = np.array([1])
print("dimention: ", arr.ndim)

arr = np.array([[1,2,3]])
print("dimention: ", arr.ndim)

arr = np.array([[[1,2,3.4,5]]])
print("dimention: ", arr.ndim)

arr = np.array([[[[1,2,3.4,5]]]])
print("dimention: ", arr.ndim)

dimention:  1
dimention:  2
dimention:  3
dimention:  4


In [7]:
import numpy as np
result = np.full((2,3),7)
print(result)

[[7 7 7]
 [7 7 7]]


In [6]:
import numpy as np
import time

n = 1000
list1 = list(range(n))
list2 = list(range(n))

start = time.time()
result_list = [ list1[i], list2[i] for i in range(n)]
list_time = time.time()- start


arr1 = np.arange(n)
arr2= np.arange(n)

start = time.time()
result_arr = arr1 + arr2
numpy_time = time.time()-start

print(f"List Time : {list-time :.6f} sec")

print(f"NumpyTime : {numpy_time:. 6f} sec")

print (f"Numpy is approx {list_time/numpy_time:.2f}x faster")

SyntaxError: did you forget parentheses around the comprehension target? (3260952483.py, line 9)

In [5]:
import numpy as np
arr = np.random.randint(0,10,(10,10))
print(arr)

[[4 3 5 1 8 8 7 9 7 9]
 [3 6 6 3 9 6 6 1 4 2]
 [5 4 4 0 7 4 4 0 8 5]
 [9 1 2 2 3 5 7 9 1 4]
 [0 7 5 2 9 8 0 0 6 9]
 [7 3 9 0 8 3 7 1 9 1]
 [5 9 5 2 8 3 8 8 3 4]
 [5 5 3 5 6 3 5 1 3 5]
 [2 9 5 9 0 4 8 4 2 3]
 [8 5 2 4 3 3 5 8 1 3]]


In [9]:
import numpy as np
arr = [1,2,3,4,[5,6,7],8,9]
print(arr[4][1])



6


In [ ]:
import numpy as np
arr = np.array([25,26,19,45,20,12,14,13,17,41,36,39])
print(arr[arr<20])



[19 12 14 13 17]


In [22]:
import numpy as np
arr = np.array([25,26,19,45,20,12,14,13,17,41,36,39])
a = [1,2,3]
b = [4,5,6]
c = a + b

In [16]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(arr[0:2,0:3])

arr = ([1,2,3,4,5,6,7,8,9])
a = [1,2,3]
arr[a]

[[1 2 3]
 [4 5 6]]


TypeError: list indices must be integers or slices, not list

In [10]:
import numpy as np
arr = np.random.rand(5,3)
print(arr)
# arr = np.random.choice(a,(10,10), replace=True, p=[0.8,0.2])
# print(arr)

[[0.82679769 0.75867884 0.43960501]
 [0.89283822 0.11010377 0.75624822]
 [0.34479322 0.89374106 0.44584029]
 [0.47547461 0.60963212 0.9403329 ]
 [0.44891844 0.41666439 0.6983941 ]]


In [7]:
arr = np.array([1,2])
print(arr)

[1 2]


In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(np.zeros)
print(arr)



(2, 3)
2
6
int64
<built-in function zeros>
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr = np.arange(0,100,2)
print(arr)



[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
