In [60]:
import numpy as np
arr = np.array([[
    [1,2],   #-2
    [3,4],
],
[
    [5,6],
    [7,8],   #-1
]
])
# print(arr)
# print(arr.shape)
# print(arr.ndim)
# print(arr[1,1,1])
# print(arr[1,0,1])
# print(arr[0,1,0])
# print(arr[-2,1,0])
# print(arr[-1,1,1])
# print(arr[0:1,:,:])
# print(arr[1:,:,:])
# print(arr[:,:1,:])
# print(arr[:,1:,:])
print(arr[:,:,:1])
print(arr[:,:,1:])

[[[1]
  [3]]

 [[5]
  [7]]]
[[[2]
  [4]]

 [[6]
  [8]]]


In [83]:
arr = np.array([[
    [1,2],   #-2
    [3,4],
],
[
    [5,6],
    [7,8],   #-1
]
])
# print(arr[-1])
# print(arr[-2])
# print(arr[-1,0,1])
# print(arr[-2,1,0])
# print(arr[:,-1:,])
# print(arr[:,:,-1])
# print(arr[:,:,-2])
print(arr[-1,1,:])
print(arr[-2,1,:])
print(arr[-1,1,:])
print(arr[:,1,1:])
print(arr[:,0,1:])

[7 8]
[3 4]
[7 8]
[[4]
 [8]]
[[2]
 [6]]


In [84]:
arr = np.array([1,2,3,4])
np.median(arr)

np.float64(2.5)