In [7]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
])
arr.flatten(order = 'C')
arr = np.ravel(arr)
arr



array([1, 2, 3, 4, 5, 6])

In [10]:
arr = np.array([[[[1,2,3]]]])
for i in np.nditer(arr):
    print(i)

for i,j in np.ndenumerate(arr):
    print(i,j)   

1
2
3
(0, 0, 0, 0) 1
(0, 0, 0, 1) 2
(0, 0, 0, 2) 3


In [11]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    ])
for i in np.nditer(arr):
    print(i)

for i,j in np.ndenumerate(arr):
    print(i,j) 

1
2
3
4
5
6
7
8
9
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [21]:
arr = np.array(
    [1,2,3,4,5,6,7,8]
)
arr = np.split(arr,2)
arr

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [23]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
])
arr1 = np.split(arr,2, axis=1)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr = np.array([1,2,3,4])
arr1 = np.transpose(arr)
arr1


array([1, 2, 3, 4])

In [ ]:
arr = np.array([1,5,8,2,5,4])
arr1 = np.sort(arr)
arr1

arr = np.array([1,5,8,2,5,4])
arr1 = np.sort(arr)
arr1

array([1, 2, 4, 5, 5, 8])

In [36]:
arr = np.array([1,5,8,2,5,4])
arr1 = np.where(arr%2==0,0,arr)
arr1

arr = np.array([[1,5,8,2,5,4]])
arr1 = np.where(arr%2==0,0,arr)
arr1

array([[1, 5, 0, 0, 5, 0]])

In [40]:
arr = np.array([1,5,8,2,5,4])
arr1 = np.delete(arr,2)
arr1

array([1, 5, 2, 5, 4])

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr1 = np.delete(arr, 5)
arr1

arr1 = np.delete(arr, 1, axis=1)    #row and colun delete
arr1

arr1 = np.delete(arr, np.where(arr>5))
arr1

array([4, 5, 6, 7, 8, 9])

In [50]:
# arr = np.array([1,2,3,4,5],
#                [1,99,2,3,4,5])
# arr1 = np.insert(arr,[2,5])
# arr1

In [54]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr1 = np.insert(arr,2,[1,2,5], axis=1)
arr1

arr1 = np.insert(arr,2,99, axis=1)
arr1

array([[ 1,  2, 99,  3],
       [ 4,  5, 99,  6],
       [ 7,  8, 99,  9]])

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])