In [28]:
import numpy as np
             #-5 -4 -3 -2 -1
arr = np.array([[1,2,3,4,5],       #-5
               [6,7,8,9,10],       #-4
               [11,12,13,14,15],   #-3
               [16,17,18,19,20],   #-2
               [21,22,23,24,25],   #-1
               ])
# print(arr)
# print("positive indexing :" , arr[3,2])
# print("negetive indexing :" ,arr[-1,-2])
# print(arr[0:2,1:4])
# print(arr[2:4,3:6])
#negetive slicing
# print(arr[-2:,-4:-2])
print(arr[-1:-3:-1,-3:-5:-1])





[[23 22]
 [18 17]]


In [43]:
             #-5 -4 -3 -2 -1
arr = np.array([[1,2,3,4,5],       #-5
               [6,7,8,9,10],       #-4
               [11,12,13,14,15],   #-3
               [16,17,18,19,20],   #-2
               [21,22,23,24,25],   #-1
               ])
arr[1,4] = 100

arr[2,1] = 200
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9, 100],
       [ 11, 200,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [48]:
arr = np.array([[1,2,3,4,5],       #-5
               [6,7,8,9,10],       #-4
               [11,12,13,14,15],   #-3
               [16,17,18,19,20],   #-2
               [21,22,23,24,25],   #-1
               ])
arr[0:1, 1:3] = 1000
print(arr)

[[   1 1000 1000    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19   20]
 [  21   22   23   24   25]]


In [44]:
arr = np.array([1,2,3,4,5])
print(arr[: : -1])


[5 4 3 2 1]


In [75]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([4,5,6,7,8])

# print(np.add(arr , arr1))
# print(np.subtract(arr , arr1))
# print(np.multiply(arr , arr1))
# print(np.divide(arr , arr1))
# print(np.power(arr , arr1))
# print(np.sqrt(arr ))
print(np.abs(arr))
print(np.mod(arr,arr1))

[1 2 3 4 5]
[1 2 3 4 5]


In [55]:
arr = np.arange(2,21, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]
