In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr2 = np.array([10, 20, 30, 40])

print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)
print("Dimensions:", arr2.ndim)

Shape: (4,)
Size: 4
Data Type: int64
Dimensions: 1


In [4]:
# 3. Create a zeros array (3×3)
zeros_arr = np.zeros((3,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 4. Create a ones array (4×2)
ones_arr = np.ones((4,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:

# 5. Create an identity matrix (5×5)
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# 6. Create a range array (10 to 50 step 5)
range_arr = np.arange(10, 51, 5)
print(range_arr)

[10 15 20 25 30 35 40 45 50]


In [8]:
# 7. Create evenly spaced values (11 numbers between 0 and 100)
even_arr = np.linspace(0, 100, 11)
print(even_arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [2]:
import numpy as np
a = np.array([0.1])
b = np.array([0.2])
c = a + b
print(c)


[0.3]
