In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,4,7,11,59,8,9,10])
print(arr)

In [ ]:
arr2 = np.array([10, 20, 30, 40])

print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)
print("Dimensions:", arr2.ndim)

Shape: (4,)
Size: 4
Data Type: int64
Dimensions: 1


In [ ]:
# 3. Create a zeros array (3×3)
zeros_arr = np.zeros((3,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 4. Create a ones array (4×2)
ones_arr = np.ones((4,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:

# 5. Create an identity matrix (5×5)
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# 6. Create a range array (10 to 50 step 5)
range_arr = np.arange(10, 51, 5)
print(range_arr)

[10 15 20 25 30 35 40 45 50]


In [ ]:
# 7. Create evenly spaced values (11 numbers between 0 and 100)
even_arr = np.linspace(0, 100, 11)
print(even_arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
import numpy as np
a = np.array([0.1])
b = np.array([0.2])
c = a + b
print(c)


[0.3]


# pandas practice #

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([14,21,44,30,25])
for i in s:
    print(i)

14
21
44
30
25


In [ ]:
for i,v in s.items():
    print(i,v)

0 14
1 21
2 44
3 30
4 25


In [ ]:
def sq(x):
    return x*x
print(s.apply(sq))

0     196
1     441
2    1936
3     900
4     625
dtype: int64


In [ ]:
s = pd.Series([1,2,5,3,7,4,9])
s.astype(float)

0    1.0
1    2.0
2    5.0
3    3.0
4    7.0
5    4.0
6    9.0
dtype: float64

In [ ]:
s = pd.Series([1,2,5,3,7,4,9])
#s.astype(bool)

In [ ]:
s.__len__

<bound method Series.__len__ of 0    1
1    2
2    5
3    3
4    7
5    4
6    9
dtype: int64>

In [ ]:
s.isin

<bound method Series.isin of 0    1
1    2
2    5
3    3
4    7
5    4
6    9
dtype: int64>

In [ ]:
print(7 in s)

False


In [ ]:
print(s.isin([1,4,9]))

0     True
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool


In [ ]:
s.unique()

array([1, 2, 5, 3, 7, 4, 9])

In [ ]:
s.is_unique()

TypeError: 'bool' object is not callable

In [ ]:
sorted(s)

[1, 2, 3, 4, 5, 7, 9]