In [ ]:
import numpy as np

# 1. Checkerboard Pattern
arr1 = np.zeros((8,8), dtype=int)
arr1[::2, 1::2] = 1
arr1[1::2, ::2] = 1.
print(arr1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
import numpy as np
arr = np.array([1,2,4,9,6,7])
a.max()
a.min()
b=np.arange(1,10)
np.setdiff1d(b,arr)

AttributeError: 'list' object has no attribute 'max'

In [9]:
#extract multiples of 3
import numpy as np
arr = np.arange(1,101)
arr = arr[arr % 3 == 0]
print(arr)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [11]:
#find commaon elements 
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

result = np.intersect1d(a, b)

print(result)

[4 5]


In [12]:
#find missing number
arr=np.array([1,2,4,6,7,9])
a.max()
a.min()
b=np.arange(1,10)
np.setdiff1d(b,arr)

array([3, 5, 8])

In [13]:
#Row-Wise maximum
import numpy as np
arr = np.array([
    [4,8,2],
    [9,1,5],
    [7,6,3]
])
result = np.max(arr, axis=1)
print(result)

[8 9 7]


In [14]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

result = np.sum(arr, axis=0)

print(result)

[12 15 18]


In [1]:
import numpy as np
arr = np.array([
    [4,8,2],
    [9,1,5],
    [7,6,3]
])
max_row = np.max(arr,axis=1)
print(max_row)

[8 9 7]


In [ ]:
import numpy as np
d = np.array([1,2,4,9,6,7])
norm_data=(d-d.min() / (d.max)-d.min())
print(norm_data)

TypeError: unsupported operand type(s) for /: 'int' and 'builtin_function_or_method'

In [18]:
import numpy as np
arr = np.array([1,2,3,4,2,5,6,1,7])
v , c = np.unique(arr,return_counts=True)
print(v,c)
v[c>1]

[1 2 3 4 5 6 7] [2 2 1 1 1 1 1]


array([1, 2])

In [19]:
import numpy as np
nums = np.arange(1,11)
print("original matrix", nums)
print("row matrix", nums[np.newaxis,:])

original matrix [ 1  2  3  4  5  6  7  8  9 10]
row matrix [[ 1  2  3  4  5  6  7  8  9 10]]
