In [1]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
import numpy as np
arr = np.arange(1,11)
print(arr.shape)

(10,)


In [3]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr = np.ones((4,1))
arr

array([[1.],
       [1.],
       [1.],
       [1.]])

In [12]:
arr = np.eye(10)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
arr = np.arange(10,51,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
arr = np.linspace(0,100,11)
arr

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

arr = np.arange(1,13).reshape(3,4)
arr

In [24]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [26]:
arr = np.array([1,2,3,4,5])
print(arr[-1])

5


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr[5:11])

[ 6  7  8  9 10 11]


In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr[::-1])

[13 12 11 10  9  8  7  6  5  4  3  2  1]


In [29]:
arr = np.array([1,2,3,4,5])
print(np.max(arr))

5


In [30]:
arr = np.array([1,2,3,4,5])
print(np.min(arr))

1


In [31]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

15


In [32]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

3.0


In [33]:
arr = np.array([1,2,3,4,5])
print(np.median(arr))

3.0


In [34]:
arr = np.array([1,2,3,4,5])
print(np.std(arr))

1.4142135623730951


In [35]:
arr = np.array([1,2,3,4,5])
print(arr ** 2)

[ 1  4  9 16 25]


In [40]:
arr = np.array([1,2,3,4,5])
print(arr[arr % 2 == 0])



[2 4]


In [41]:
arr = np.arange(1,21)
print(arr[arr%2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [43]:
arr = np.arange(1,21)
print(np.sum(arr>5))

15


In [44]:
arr = np.arange(1,21)
print(arr.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [46]:
arr = np.array([
    [1,2],
    [3,4]
])
print(np.sum(arr, axis=1))

[3 7]


In [47]:
arr = np.array([
    [1,2],
    [3,4]
])
print(np.sum(arr, axis=0))

[4 6]


In [54]:
arr = np.arange(1,21)

print(arr1[arr % 2 != 0] == -1)


TypeError: 'int' object is not subscriptable

In [ ]:
arr = np.arange(1,10)

print(np.argmax(arr))

8


In [3]:
import numpy as np
arr = np.random.randint(1,11,5)
arr

array([10,  5,  2,  4, 10], dtype=int32)