In [30]:
import numpy as np

In [31]:
arr = np.arange(100,-20,-1)
arr

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,
        -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14, -15, -16,
       -17, -18, -19])

In [32]:
import time

size = 1000
li = list(range(size))
st = time.time()
li = [i * 2 for i in li ]
et = time.time() - st

arr = np.arange(size)
at = time.time()
ai = arr * 2
kt = time.time() - at

print("total time taken by list", et)
print("total time taken by arr", kt)

total time taken by list 0.0021245479583740234
total time taken by arr 0.0034008026123046875


In [33]:
arr =  np.arange(20, -41, -1)
arr

array([ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,   9,   8,
         7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,
        -6,  -7,  -8,  -9, -10, -11, -12, -13, -14, -15, -16, -17, -18,
       -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31,
       -32, -33, -34, -35, -36, -37, -38, -39, -40])

In [34]:
a = [10,20,30]

arr = np.array(a)
print(type(arr))

arr = np.array([12,45,63])
print(arr)

<class 'numpy.ndarray'>
[12 45 63]


In [35]:
k = list(range(100,201))
arr = np.array(k)
print(arr)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


In [36]:
k = list(range(0,11,2))
arr = np.array(k)
print(arr)

[ 0  2  4  6  8 10]


In [37]:
arr = np.array([12,34.54,"56",78])

print(type(arr))
arr

<class 'numpy.ndarray'>


array(['12', '34.54', '56', '78'], dtype='<U32')

In [38]:
ar = np.array([22,"33", 44, 55.8])
ar
print(len(ar))
print(ar.shape)
print(ar.ndim)
print(ar.size)

4
(4,)
1
4


In [40]:
a = np.array([34,67,89,90])
print(a.itemsize * a.size)


32
