In [ ]:

# Q1 wap to create 2d array of first 10 odd number
# Q2 use arange function to create a 2d matrix of shape (2,40),(4,16),(3,9)
# Q3 create a 2d array of shape (4,4) in which all elememt should ve divisible by 5
# Q4 create a identity matrix of (5,5) of integer element in which diaonal should satrt from 2 row 
# Q5 create a 2d array of (3,3) matrix and convert all vales to they square

In [1]:
import numpy as np

In [6]:
a = np.arange(1,20,2).reshape(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:

m1 = np.arange(80).reshape(2, 40)
m2 = np.arange(64).reshape(4, 16)
m3 = np.arange(27).reshape(3, 9)

# Verify the shapes
print("Matrix 1 shape:", m1.shape)
print("Matrix 2 shape:", m2.shape)
print("Matrix 3 shape:", m3.shape)



Matrix 1 shape: (2, 40)
Matrix 2 shape: (4, 16)
Matrix 3 shape: (3, 9)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79]])

In [9]:

a = np.arange(0, 80, 5).reshape(4, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

In [11]:
arr = np.eye(5, k = 2)
arr

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr = np.arange(1,10).reshape(3,3)
arr1 = arr ** 2
arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])