In [1]:

# Q1 wap to create 2d array of first 10 odd number
# Q2 use arange function to create a 2d matrix of shape (2,40),(4,16),(3,9)
# Q3 create a 2d array of shape (4,4) in which all elememt should ve divisible by 5
# Q4 create a identity matrix of (5,5) of integer element in which diaonal should satrt from 2 row 
# Q5 create a 2d array of (3,3) matrix and convert all vales to they square

In [2]:
import numpy as np

In [3]:
a = np.arange(1,20,2).reshape(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [4]:

m1 = np.arange(80).reshape(2, 40)
m2 = np.arange(64).reshape(4, 16)
m3 = np.arange(27).reshape(3, 9)

# Verify the shapes
print("Matrix 1 shape:", m1.shape)
print("Matrix 2 shape:", m2.shape)
print("Matrix 3 shape:", m3.shape)



Matrix 1 shape: (2, 40)
Matrix 2 shape: (4, 16)
Matrix 3 shape: (3, 9)


In [5]:

a = np.arange(0, 80, 5).reshape(4, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

In [6]:
arr = np.eye(5, k = 2)
arr

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
arr = np.arange(1,10).reshape(3,3)
arr1 = arr ** 2
arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [8]:
arr = np.random.rand(0,1)
print(arr)

[]


In [ ]:
# # task
# Q1 create a 1d array of 20 random integr number and extracte or filter all the numbers by divisible by 3 
# Q2 cerate an array of 15 random integers between 10 to 100 replace aal value 50> with -1 using boolena indexing 
# Q3 cerate a (4,4) array and use ittreter to square each element and print seperatelty
# Q4 create a 1d array and extered 2 and 4 element using indexing 
# Q5 genearey a (2,5) array of random float beetween 0 or 1

In [12]:
a = np.random.randint(10,40,10)
print(a[a%3==0])


[15 24 27 30 15]


In [ ]:
a = np.random.randint(10,100,15)
a[a>50]= -1
print(a)



[13 -1 -1 46 -1 -1 44 -1 42 17 -1 -1 44 -1 15]


In [23]:
arr = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                [24,50,89],
                ])
arr
for i in arr:
    for j in i:
        print(j**2)

144
1156
3025
3136
7744
144
196
8100
9801
576
2500
7921


In [25]:
arr = np.array([1,2,3,4,5,6])
print(arr[[1,3]])


[2 4]


In [26]:
arr = np.random.rand(2, 5)
arr

array([[0.83269295, 0.10005764, 0.90603416, 0.70417586, 0.91956614],
       [0.97731002, 0.93193532, 0.56628556, 0.5106963 , 0.56561692]])