In [1]:

# Q1 wap to create 2d array of first 10 odd number
# Q2 use arange function to create a 2d matrix of shape (2,40),(4,16),(3,9)
# Q3 create a 2d array of shape (4,4) in which all elememt should ve divisible by 5
# Q4 create a identity matrix of (5,5) of integer element in which diaonal should satrt from 2 row 
# Q5 create a 2d array of (3,3) matrix and convert all vales to they square

In [2]:
import numpy as np

In [3]:
a = np.arange(1,20,2).reshape(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [4]:

m1 = np.arange(80).reshape(2, 40)
m2 = np.arange(64).reshape(4, 16)
m3 = np.arange(27).reshape(3, 9)

# Verify the shapes
print("Matrix 1 shape:", m1.shape)
print("Matrix 2 shape:", m2.shape)
print("Matrix 3 shape:", m3.shape)



Matrix 1 shape: (2, 40)
Matrix 2 shape: (4, 16)
Matrix 3 shape: (3, 9)


In [5]:

a = np.arange(0, 80, 5).reshape(4, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

In [6]:
arr = np.eye(5, k = 2)
arr

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
arr = np.arange(1,10).reshape(3,3)
arr1 = arr ** 2
arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [8]:
arr = np.random.rand(0,1)
print(arr)

[]


In [9]:
# # task
# Q1 create a 1d array of 20 random integr number and extracte or filter all the numbers by divisible by 3 
# Q2 cerate an array of 15 random integers between 10 to 100 replace aal value 50> with -1 using boolena indexing 
# Q3 cerate a (4,4) array and use ittreter to square each element and print seperatelty
# Q4 create a 1d array and extered 2 and 4 element using indexing 
# Q5 genearey a (2,5) array of random float beetween 0 or 1

In [10]:
a = np.random.randint(10,40,10)
print(a[a%3==0])


[12 30 39]


In [11]:
a = np.random.randint(10,100,15)
a[a>50]= -1
print(a)



[-1 -1 12 -1 -1 45 -1 -1 32 -1 49 -1 20 33 -1]


In [12]:
arr = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                [24,50,89],
                ])
arr
for i in arr:
    for j in i:
        print(j**2)

144
1156
3025
3136
7744
144
196
8100
9801
576
2500
7921


In [13]:
arr = np.array([1,2,3,4,5,6])
print(arr[[1,3]])


[2 4]


In [14]:
arr = np.random.rand(2, 5)
arr

array([[0.1216854 , 0.55375896, 0.35315467, 0.17473901, 0.04824529],
       [0.32704548, 0.89952303, 0.84410182, 0.24995821, 0.57256659]])

In [15]:
## task=22/09/2026
# Q1 create matrix using sliceing
# 111
# 222
# 333

# Q2 create a null vecoter of size 10
# Q3 of size 10 and change the 5th element to 5
#Q 4  create a 1d array of 10 randon numbers and reverse the matrix without using function 
# Q5 
# create  1111
#         5227
#         6667

In [16]:
# Q1 create matrix using sliceing
arr = np.zeros((3,3), dtype=int)
arr
arr[0:1, 0:] =  1
arr[1:2, :] = 2
arr[-1, :] = 3
arr


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [17]:
# Q2 create a null vecoter of size 10
arr = np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Q3 of size 10 and change the 5th element to 5
arr = np.zeros(10, dtype=int)

arr[4] = 5
arr

array([0, 0, 0, 0, 5, 0, 0, 0, 0, 0])

In [19]:
#Q 4  create a 1d array of 10 randon numbers and reverse the matrix without using function 

ar = np.random.randint(10,30,10)
ar
print(ar[::-1])

[25 19 24 16 26 11 16 10 14 15]


In [20]:
# Q5 
# create  1111
#         5227
#         6667
arr = np.zeros((3,4), dtype=int)

arr
arr[0:1, 0:] =  1
arr[1: , -1] =  7
arr[1:2 , 1:3] =  2
arr[1: 2, 0:1] =  5
arr[-1 , 0:3] =  6
arr

array([[1, 1, 1, 1],
       [5, 2, 2, 7],
       [6, 6, 6, 7]])

In [21]:
# 23 sept
#Q1 : Create a (2,3), (3,4), (5,5), (6,4) array with random integers 
#Q2  create a 4,4 matrix of zeroes and convert all zeroes to 5 using (np.where function)
#Q3 : create a 4,4 random int no. and broadcast all elements of the matrix to their cube
#Q4 : create a 1d array of 10 random elem betweem 50 to 100 and replace all values greater than 70 to -1 and 
# other values to 5 .

#Q5: create a 3,3 matrix from 50 to 200 with linearspace 


In [22]:
arr = np.random.randint(0,7 , (2,3))
arr = np.random.randint(17,30 , (3,4))
arr = np.random.randint(10,30 , (5,5))
arr = np.random.randint(50,70 , (6,4))
arr

array([[56, 64, 53, 53],
       [66, 56, 55, 58],
       [69, 63, 66, 61],
       [50, 64, 56, 54],
       [55, 50, 59, 50],
       [63, 55, 62, 62]], dtype=int32)

In [23]:


# Q2
# Create a 4x4 matrix of zeroes
# and convert all zeroes to 5 using np.where()

arr = np.zeros((4, 4), dtype=int)

arr = np.where(arr == 0, 5, arr)
print(arr)




[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
# Q3
# Create a 4x4 random integer matrix
# and cube all elements using broadcasting

arr = np.random.randint(1, 10, (4, 4))
arr = arr ** 3

print(arr)




[[  8 512   8 216]
 [  8  64 729  27]
 [ 27   1 343   8]
 [  8 343 343 125]]


In [25]:
# Q4
# Create a 1D array of 10 random elements
# between 50 and 100
# > 70 -> -1
# other values -> 5

arr = np.random.randint(50, 101, 10)

arr = np.where(arr > 70, -1, 5)

print(arr)




[-1 -1 -1  5  5 -1 -1 -1  5  5]


In [26]:
# Q5
# Create a 3x3 matrix from 50 to 200 using linspace

arr = np.linspace(50, 200, 9).reshape(3, 3)
print(arr)

[[ 50.    68.75  87.5 ]
 [106.25 125.   143.75]
 [162.5  181.25 200.  ]]


In [28]:
arr = np.full((5,5) ,0)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
arr = np.full((5,5) ,0)
arr[0:1, 2:]= 8
arr[1:4 , 0:1]= 7
arr[1:4 , 1:3]= 5
arr

array([[0, 0, 8, 8, 8],
       [7, 5, 5, 0, 0],
       [7, 5, 5, 0, 0],
       [7, 5, 5, 0, 0],
       [0, 0, 0, 0, 0]])