In [36]:
import numpy as np

In [37]:
a = np.array([[1,3,6],
             [9,10,11]
])
a
print(a.ndim)

2


In [38]:
a = np.array([[1,3,6,9,33,12],
             [9,10,11,15,44,61],
             
])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  3  6  9 33 12]
 [ 9 10 11 15 44 61]]
(2, 6)
2


In [39]:
# arange function

arr = np.arange(0,10,2)
arr


array([0, 2, 4, 6, 8])

In [40]:
arr1 = np.arange(0,9).reshape(3,3)
arr1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
ar = np.arange(0,12,2).reshape(2,3)

ar.shape
ar.ndim

2

In [42]:
# identity matrix

i = np.eye(5)
print(i)
i.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [43]:
i = np.eye(10,k = 2)
print(i)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [44]:
# random function

print(np.random.random(1))
print(np.random.randint(60,100,10))
a = np.random.randint(20, 50, size=(4, 4))
a = np.random.randint(20, 50, 16).reshape(4,4)


print(a)

[0.42155099]
[63 77 81 63 71 99 95 92 80 72]
[[25 29 21 23]
 [32 24 41 25]
 [25 25 46 20]
 [49 49 20 30]]


In [45]:
a = np.random.randint(10, 50, (2, 3))
a

array([[29, 39, 28],
       [43, 14, 17]], dtype=int32)

In [46]:
a = np.random.randint(5,6,(3, 3))
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [47]:
# linspace

print(np.linspace(0,10,5))
print(np.linspace(0,20,5, dtype=int))

[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10 15 20]


In [48]:
print(np.linspace(10,50,5, dtype=int))

[10 20 30 40 50]


In [49]:
# Q1 - convert a 1d array into 2d array with 3 rows (given = [0,1,2,3,4,5,6,7,8])
# Q2 - genrate a 1d array of 10 random integers each integer shoulb a no. betwwen 30 and 40 (inclusive)
# Q3 - create a 3,3 identity matrix
# Q4 - create a 10 by 10 array with random values between 0 to 1 (in float)
# Q5 - 

In [50]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = arr.reshape(3, 3)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
print(np.random.randint(30,40,10))

[34 36 34 31 34 35 30 30 32 32]


In [52]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
arr = np.random.rand(0,1)
print(arr)

[]


In [54]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

print(np.where(a % 2 != 0, -1, a))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [55]:
a = np.array([0,1,2,3,4,5,6,7,8])
a1 = a.reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
a = np.random.randint(202, 203, 4 ,).reshape(2, 2)
a


array([[202, 202],
       [202, 202]], dtype=int32)

In [62]:
a = np.random.randint(30,41,10)
a

array([31, 40, 38, 33, 40, 38, 31, 33, 39, 38], dtype=int32)

In [69]:
a = np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
a = np.random.randint(20,100, (10,10))
max = 0
  



In [73]:
arr = np.zeros((2,2),dtype=int)
arr


arr[0, :] = 1      
arr[-1, :] = 1    
arr[:, 0] = 1      
arr[:, -1] = 1     

print(arr)

[[1 1]
 [1 1]]


In [79]:
print(np.full((9,9),6))

[[6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]]


In [81]:
k = np.full((1,7), 8)
m = np.full((1,7), 6)
m


array([[6, 6, 6, 6, 6, 6, 6]])