In [1]:
import numpy as np

In [2]:
a = np.array([[1,3,6],
             [9,10,11]
])
a
print(a.ndim)

2


In [3]:
a = np.array([[1,3,6,9,33,12],
             [9,10,11,15,44,61],
             
])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  3  6  9 33 12]
 [ 9 10 11 15 44 61]]
(2, 6)
2


In [4]:
# arange function

arr = np.arange(0,10,2)
arr


array([0, 2, 4, 6, 8])

In [5]:
arr1 = np.arange(0,20).reshape(5,4)
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
ar = np.arange(0,12,2).reshape(2,3)

ar.shape
ar.ndim

2

In [7]:
# identity matrix

i = np.eye(5)
print(i)
i.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [8]:
i = np.eye(10,k = 2)
print(i)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
# random function

print(np.random.random(1))
print(np.random.randint(60,100,10))
a = np.random.randint(20, 50, size=(4, 4))
a = np.random.randint(20, 50, 16).reshape(4,4)


print(a)

[0.86152499]
[70 68 78 78 78 96 69 70 98 75]
[[34 32 41 20]
 [20 48 36 42]
 [46 31 40 20]
 [24 34 41 35]]


In [10]:
a = np.random.randint(10, 50, (2, 3))
a

array([[28, 22, 28],
       [31, 46, 28]], dtype=int32)

In [11]:
a = np.random.randint(5,6,(3, 3))
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [12]:
# linspace

print(np.linspace(0,10,5))
print(np.linspace(0,20,5, dtype=int))

[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10 15 20]


In [13]:
print(np.linspace(10,50,5, dtype=int))

[10 20 30 40 50]


In [14]:
# Q1 - convert a 1d array into 2d array with 3 rows (given = [0,1,2,3,4,5,6,7,8])
# Q2 - genrate a 1d array of 10 random integers each integer shoulb a no. betwwen 30 and 40 (inclusive)
# Q3 - create a 3,3 identity matrix
# Q4 - create a 10 by 10 array with random values between 0 to 1 (in float)
# Q5 - 

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = arr.reshape(3, 3)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
print(np.random.randint(30,40,10))

[34 34 32 37 36 38 39 31 38 38]


In [19]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr = np.random.rand(0,1)
print(arr)

[]
