In [1]:
import numpy as np

In [2]:
a = np.array([[1,3,6],
             [9,10,11]
])
a
print(a.ndim)

2


In [3]:
a = np.array([[1,3,6,9,33,12],
             [9,10,11,15,44,61],
             
])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  3  6  9 33 12]
 [ 9 10 11 15 44 61]]
(2, 6)
2


In [4]:
# arange function

arr = np.arange(0,10,2)
arr


array([0, 2, 4, 6, 8])

In [5]:
arr1 = np.arange(0,20).reshape(5,4)
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
ar = np.arange(0,12,2).reshape(2,3)

ar.shape
ar.ndim

2

In [7]:
# identity matrix

i = np.eye(5)
print(i)
i.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [8]:
i = np.eye(10,k = 2)
print(i)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# random function

print(np.random.random(1))
print(np.random.randint(60,100,10))
a = np.random.randint(20, 50, size=(4, 4))
a = np.random.randint(20, 50, 16).reshape(4,4)


print(a)

[0.97286057]
[89 79 67 92 68 79 99 60 94 78]
[[49 48 21 39]
 [50 25 30 29]
 [23 29 37 45]
 [48 36 29 29]]


In [17]:
a = np.random.randint(10, 50, (2, 3))
a

array([[27, 31, 26],
       [49, 41, 19]], dtype=int32)

In [25]:
a = np.random.randint(5,6,(3, 3))
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [27]:
# linspace

print(np.linspace(0,10,5))
print(np.linspace(0,20,5, dtype=int))

[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10 15 20]


In [28]:
print(np.linspace(10,50,5, dtype=int))

[10 20 30 40 50]
