In [2]:
import numpy as np

In [3]:
a = np.array([[1,3,6],
             [9,10,11]
])
a
print(a.ndim)

2


In [4]:
a = np.array([[1,3,6,9,33,12],
             [9,10,11,15,44,61],
             
])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  3  6  9 33 12]
 [ 9 10 11 15 44 61]]
(2, 6)
2


In [5]:
# arange function

arr = np.arange(0,10,2)
arr


array([0, 2, 4, 6, 8])

In [6]:
arr1 = np.arange(0,20).reshape(5,4)
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
ar = np.arange(0,12,2).reshape(2,3)

ar.shape
ar.ndim

2

In [8]:
# identity matrix

i = np.eye(5)
print(i)
i.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [9]:
i = np.eye(10,k = 2)
print(i)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
