In [1]:
import numpy as np

In [2]:
a = np.array([[1,3,6],
             [9,10,11]
])
a
print(a.ndim)

2


In [3]:
a = np.array([[1,3,6,9,33,12],
             [9,10,11,15,44,61],
             
])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  3  6  9 33 12]
 [ 9 10 11 15 44 61]]
(2, 6)
2


In [4]:
# arange function

arr = np.arange(0,10,2)
arr


array([0, 2, 4, 6, 8])

In [5]:
arr1 = np.arange(0,9).reshape(3,3)
arr1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ar = np.arange(0,12,2).reshape(2,3)

ar.shape
ar.ndim

2

In [7]:
# identity matrix

i = np.eye(5)
print(i)
i.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [8]:
i = np.eye(10,k = 2)
print(i)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
# random function

print(np.random.random(1))
print(np.random.randint(60,100,10))
a = np.random.randint(20, 50, size=(4, 4))
a = np.random.randint(20, 50, 16).reshape(4,4)


print(a)

[0.49626256]
[71 92 75 84 92 92 90 80 73 86]
[[47 35 49 21]
 [47 33 27 39]
 [48 35 20 35]
 [34 34 38 31]]


In [10]:
a = np.random.randint(10, 50, (2, 3))
a

array([[19, 39, 29],
       [16, 11, 32]], dtype=int32)

In [11]:
a = np.random.randint(5,6,(3, 3))
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [12]:
# linspace

print(np.linspace(0,10,5))
print(np.linspace(0,20,5, dtype=int))

[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10 15 20]


In [13]:
print(np.linspace(10,50,5, dtype=int))

[10 20 30 40 50]


In [14]:
# Q1 - convert a 1d array into 2d array with 3 rows (given = [0,1,2,3,4,5,6,7,8])
# Q2 - genrate a 1d array of 10 random integers each integer shoulb a no. betwwen 30 and 40 (inclusive)
# Q3 - create a 3,3 identity matrix
# Q4 - create a 10 by 10 array with random values between 0 to 1 (in float)
# Q5 - 

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = arr.reshape(3, 3)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
print(np.random.randint(30,40,10))

[37 38 38 36 38 33 33 39 35 32]


In [17]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr = np.random.rand(0,1)
print(arr)

[]


In [19]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

print(np.where(a % 2 != 0, -1, a))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [20]:
a = np.array([0,1,2,3,4,5,6,7,8])
a1 = a.reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
a = np.random.randint(202, 203, 4 ,).reshape(2, 2)
a


array([[202, 202],
       [202, 202]], dtype=int32)

In [22]:
a = np.random.randint(30,41,10)
a

array([40, 30, 37, 38, 40, 34, 37, 37, 35, 36], dtype=int32)

In [23]:
a = np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
a = np.random.randint(20,100, (10,10))
max = 0
  



In [26]:
arr = np.zeros((2,2),dtype=int)
arr


arr[0, :] = 1      
arr[-1, :] = 1    
arr[:, 0] = 1      
arr[:, -1] = 1     

print(arr)

[[1 1]
 [1 1]]


In [27]:
print(np.full((9,9),6))

[[6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]]


In [28]:
k = np.full((1,7), 8)
m = np.full((1,7), 6)
m


array([[6, 6, 6, 6, 6, 6, 6]])

In [29]:
print(np.full((9,9),6))
print(np.full((4,4), 6))


[[6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [30]:
print(np.full((5,5), 8))

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [31]:
arr = np.array([1, 2, 3])
arr
                

array([1, 2, 3])