In [3]:
import numpy as np

In [4]:
a = np.array([[1,3,6],
             [9,10,11]
])
a
print(a.ndim)

2


In [5]:
a = np.array([[1,3,6,9,33,12],
             [9,10,11,15,44,61],
             
])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  3  6  9 33 12]
 [ 9 10 11 15 44 61]]
(2, 6)
2


In [6]:
# arange function

arr = np.arange(0,10,2)
arr


array([0, 2, 4, 6, 8])

In [7]:
arr1 = np.arange(0,9).reshape(3,3)
arr1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ar = np.arange(0,12,2).reshape(2,3)

ar.shape
ar.ndim

2

In [9]:
# identity matrix

i = np.eye(5)
print(i)
i.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [10]:
i = np.eye(10,k = 2)
print(i)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
# random function

print(np.random.random(1))
print(np.random.randint(60,100,10))
a = np.random.randint(20, 50, size=(4, 4))
a = np.random.randint(20, 50, 16).reshape(4,4)


print(a)

[0.38619752]
[78 85 77 93 66 73 70 63 65 68]
[[28 42 33 23]
 [31 26 25 36]
 [41 24 40 38]
 [28 29 37 39]]


In [12]:
a = np.random.randint(10, 50, (2, 3))
a

array([[12, 11, 47],
       [19, 18, 10]], dtype=int32)

In [13]:
a = np.random.randint(5,6,(3, 3))
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [14]:
# linspace

print(np.linspace(0,10,5))
print(np.linspace(0,20,5, dtype=int))

[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10 15 20]


In [15]:
print(np.linspace(10,50,5, dtype=int))

[10 20 30 40 50]


In [16]:
# Q1 - convert a 1d array into 2d array with 3 rows (given = [0,1,2,3,4,5,6,7,8])
# Q2 - genrate a 1d array of 10 random integers each integer shoulb a no. betwwen 30 and 40 (inclusive)
# Q3 - create a 3,3 identity matrix
# Q4 - create a 10 by 10 array with random values between 0 to 1 (in float)
# Q5 - 

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = arr.reshape(3, 3)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
print(np.random.randint(30,40,10))

[32 38 37 32 33 32 34 39 35 35]


In [19]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
arr = np.random.rand(0,1)
print(arr)

[]
