In [1]:
import numpy as np

In [2]:
arr = np.array([12,45,67,89,80])

arr[1]
arr[-1]
arr[3]


np.int64(89)

In [3]:
# 2d matrix indexing

arr2 = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                ])

arr2
print(arr2[1,1])
print(arr2[2,0])
print(arr2[0,2])

88
14
55


In [4]:
# fancy indexing------------when we want more then 1 element with position

arr = np.array([12,45,67,89,80])
arr[[1,3]]
arr[[0,2,4]]
arr[[0,4,2]]


array([12, 80, 67])

In [5]:
arr = np.random.randint(10,30, (10,))
arr1 = arr[[0,9]]= 60
arr

array([60, 22, 13, 24, 19, 15, 24, 17, 16, 60], dtype=int32)

In [6]:
# boolean indexing
arr = np.array([12,45,67,89,80])
print(arr[arr>50])
print(arr[arr%2==0])


[67 89 80]
[12 80]


In [7]:
np.random.seed(42)
arr=np.random.randint(10,21,10)
print(arr)
print(arr[[1,2,7]])

[16 13 20 17 14 16 19 12 16 20]
[13 20 12]


In [8]:
arr2 = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                ])
arr2
for i in arr2:
    for j in i:
        print(j)

12
34
55
56
88
12
14
90
99


In [9]:
# nditor loop

for i in np.nditer(arr2):
    print(i)

12
34
55
56
88
12
14
90
99


## slicing


In [10]:
a = np.array([1,2,3,4,5])
a[2:6]


array([3, 4, 5])

In [11]:
arr = np.array([[12,14,50],
                [77,66,9],
                [10,2,4],
                ])
arr
print(arr[1:3,1])
print(arr[1:3,0:2])
print(arr[1:,1:])
print(arr[0:2, 0:])

print(arr[0: , 0: ])



[66  2]
[[77 66]
 [10  2]]
[[66  9]
 [ 2  4]]
[[12 14 50]
 [77 66  9]]
[[12 14 50]
 [77 66  9]
 [10  2  4]]


In [12]:
a = np.arange(0,16).reshape(4,4)
print(a)
print(a[1:2,:])
print(a[3:,:])
print(a[0:,1:3])
print(a[1:3,1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[4 5 6 7]]
[[12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6  7]
 [ 9 10 11]]


In [13]:
arr = np.zeros(10)
arr.dtype

dtype('float64')

In [14]:
arr = np.zeros(10).reshape(2,5)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
arr = np.zeros((6,6),dtype=int)
arr


arr[0, :] = 1      
arr[-1, :] = 1    
arr[:, 0] = 1      
arr[:, -1] = 1     

print(arr)


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [17]:
# np.where() 

ar = np.array([12,45,67,89,80])
print(ar)

print(np.where(ar>50))


print(np.where(ar>50, -1, ar))


[12 45 67 89 80]
(array([2, 3, 4]),)
[12 45 -1 -1 -1]


In [ ]:
np.random.seed(42)                    # random value (static)

arr = np.random.randint(0, 10, (3, 3))

arr

print(np.where(arr % 2 == 0, 0, 1))

[[0 1 1]
 [0 0 1]
 [0 0 1]]


In [33]:
# broadcasting 

np.random.seed(42)                            # random value (static)
arr = np.random.randint(0, 10, (3, 3))
arr

for i in arr:
    i += 10
print(arr)    


for i in np.nditer(arr):
    print(i)



[[16 13 17]
 [14 16 19]
 [12 16 17]]
16
13
17
14
16
19
12
16
17


In [34]:
for i in np.nditer(arr):
    if i%2==0:
        print(i + 10)

26
24
26
22
26


In [ ]:
# broadcasting 

print(arr + 10)

print(arr ** 2)


[[26 23 27]
 [24 26 29]
 [22 26 27]]
[[256 169 289]
 [196 256 361]
 [144 256 289]]


In [40]:
arr = np.random.randint(0,2, (3, 3))
arr

array([[0, 1, 1],
       [1, 0, 1],
       [0, 1, 1]], dtype=int32)

In [42]:
arr = np.random.random(9).reshape(3,3)
arr

array([[0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041]])

In [43]:
arr = np.random.randint(10,20, (4, 4))
arr

array([[12, 16, 14, 18],
       [16, 11, 13, 18],
       [11, 19, 18, 19],
       [14, 11, 13, 16]], dtype=int32)

array([[96, 84, 63, 66],
       [85, 99, 89, 53],
       [51, 55, 91, 53],
       [78, 67, 75, 93]], dtype=int32)