In [2]:
import numpy as np

In [3]:
arr = np.array([12,45,67,89,80])

arr[1]
arr[-1]
arr[3]


np.int64(89)

In [4]:
# 2d matrix indexing

arr2 = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                ])

arr2
print(arr2[1,1])
print(arr2[2,0])
print(arr2[0,2])

88
14
55


In [5]:
# fancy indexing------------when we want more then 1 element with position

arr = np.array([12,45,67,89,80])
arr[[1,3]]
arr[[0,2,4]]
arr[[0,4,2]]


array([12, 80, 67])

In [6]:
arr = np.random.randint(10,30, (10,))
arr1 = arr[[0,9]]= 60
arr

array([60, 18, 19, 15, 22, 19, 11, 18, 21, 60], dtype=int32)

In [7]:
# boolean indexing
arr = np.array([12,45,67,89,80])
print(arr[arr>50])
print(arr[arr%2==0])


[67 89 80]
[12 80]


In [8]:
np.random.seed(42)
arr=np.random.randint(10,21,10)
print(arr)
print(arr[[1,2,7]])

[16 13 20 17 14 16 19 12 16 20]
[13 20 12]


In [9]:
arr2 = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                ])
arr2
for i in arr2:
    for j in i:
        print(j)

12
34
55
56
88
12
14
90
99


In [10]:
# nditor loop

for i in np.nditer(arr2):
    print(i)

12
34
55
56
88
12
14
90
99


## slicing


In [13]:
a = np.array([1,2,3,4,5])
a[2:6]


array([3, 4, 5])

In [ ]:
arr = np.array([[12,14,50],
                [77,66,9],
                [10,2,4],
                ])
arr
print(arr[1:3,1])
print(arr[1:3,0:2])
print(arr[1:,1:])
print(arr[0:2, 0:])

print(arr[0: , 0: ])



[66  2]
[[77 66]
 [10  2]]
[[66  9]
 [ 2  4]]
[[12 14 50]
 [77 66  9]]
[[12 14 50]
 [77 66  9]
 [10  2  4]]
[[12 14 50]
 [77 66  9]]
