In [1]:
import numpy as np

In [ ]:
arr = np.array([12,45,67,89,80])

arr[1]
arr[-1]
arr[3]


(np.int64(89), [2])

In [14]:
# 2d matrix indexing

arr2 = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                ])

arr2
print(arr2[1,1])
print(arr2[2,0])
print(arr2[0,2])

88
14
55


In [22]:
# fancy indexing------------when we want more then 1 element with position

arr = np.array([12,45,67,89,80])
arr[[1,3]]
arr[[0,2,4]]
arr[[0,4,2]]


array([12, 80, 67])

In [34]:
arr = np.random.randint(10,30, (10,))
arr1 = arr[[0,9]]= 60
arr

array([60, 25, 29, 12, 12, 18, 15, 17, 19, 60], dtype=int32)

In [39]:
# boolean indexing
arr = np.array([12,45,67,89,80])
print(arr[arr>50])
print(arr[arr%2==0])


[67 89 80]
[12 80]


In [40]:
np.random.seed(42)
arr=np.random.randint(10,21,10)
print(arr)
print(arr[[1,2,7]])

[16 13 20 17 14 16 19 12 16 20]
[13 20 12]


In [44]:
arr2 = np.array([[12,34,55],
                [56,88,12],
                [14,90,99],
                ])
arr2
for i in arr2:
    for j in i:
        print(j)

12
34
55
56
88
12
14
90
99
