In [1]:
import numpy as np

In [2]:
a = np.array([[1,3,6],
             [9,10,11]
])
a
print(a.ndim)

2


In [3]:
a = np.array([[1,3,6,9,33,12],
             [9,10,11,15,44,61],
             
])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  3  6  9 33 12]
 [ 9 10 11 15 44 61]]
(2, 6)
2


In [4]:
# arange function

arr = np.arange(0,10,2)
arr


array([0, 2, 4, 6, 8])

In [5]:
arr1 = np.arange(0,9).reshape(3,3)
arr1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ar = np.arange(0,12,2).reshape(2,3)

ar.shape
ar.ndim

2

In [7]:
# identity matrix

i = np.eye(5)
print(i)
i.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [8]:
i = np.eye(10,k = 2)
print(i)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
# random function

print(np.random.random(1))
print(np.random.randint(60,100,10))
a = np.random.randint(20, 50, size=(4, 4))
a = np.random.randint(20, 50, 16).reshape(4,4)


print(a)

[0.22672041]
[98 77 94 64 77 79 67 61 86 89]
[[33 40 24 43]
 [43 49 36 35]
 [36 33 47 48]
 [42 41 41 27]]


In [10]:
a = np.random.randint(10, 50, (2, 3))
a

array([[43, 30, 43],
       [43, 40, 43]], dtype=int32)

In [11]:
a = np.random.randint(5,6,(3, 3))
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [12]:
# linspace

print(np.linspace(0,10,5))
print(np.linspace(0,20,5, dtype=int))

[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10 15 20]


In [13]:
print(np.linspace(10,50,5, dtype=int))

[10 20 30 40 50]


In [14]:
# Q1 - convert a 1d array into 2d array with 3 rows (given = [0,1,2,3,4,5,6,7,8])
# Q2 - genrate a 1d array of 10 random integers each integer shoulb a no. betwwen 30 and 40 (inclusive)
# Q3 - create a 3,3 identity matrix
# Q4 - create a 10 by 10 array with random values between 0 to 1 (in float)
# Q5 - 

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = arr.reshape(3, 3)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
print(np.random.randint(30,40,10))

[39 30 36 30 39 30 39 35 35 30]


In [17]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr = np.random.rand(0,1)
print(arr)

[]


In [19]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

print(np.where(a % 2 != 0, -1, a))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [20]:
a = np.array([0,1,2,3,4,5,6,7,8])
a1 = a.reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
a = np.random.randint(202, 203, 4 ,).reshape(2, 2)
a


array([[202, 202],
       [202, 202]], dtype=int32)

In [22]:
a = np.random.randint(30,41,10)
a

array([32, 40, 40, 34, 34, 33, 37, 36, 32, 38], dtype=int32)

In [23]:
a = np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
a = np.random.randint(20,100, (10,10))
max = 0
  



In [26]:
arr = np.zeros((2,2),dtype=int)
arr


arr[0, :] = 1      
arr[-1, :] = 1    
arr[:, 0] = 1      
arr[:, -1] = 1     

print(arr)

[[1 1]
 [1 1]]


In [27]:
print(np.full((9,9),6))

[[6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]]


In [28]:
k = np.full((1,7), 8)
m = np.full((1,7), 6)
m


array([[6, 6, 6, 6, 6, 6, 6]])

In [29]:
print(np.full((9,9),6))
print(np.full((4,4), 6))


[[6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [30]:
print(np.full((5,5), 8))

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [31]:
arr = np.array([1, 2, 3])
arr
                

array([1, 2, 3])

In [32]:
a = np.array([1,2,None])
a = np.array([1,2,np.nan])
a

array([ 1.,  2., nan])

In [33]:
a = np.array([[1,2,np.nan],[3,np.nan,6]])
a

#isnan 

print(np.sum(np.isnan(a)))

    

2


In [34]:
a = np.random.randint(1,21,10)
a
print(a.mean())
np.mean(a)
np.median(a)
np.std(a)
np.var(a)

11.3


np.float64(33.81)

In [35]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.mean(arr)

In [36]:
np.mean(arr)

np.mean(arr,axis=0)   # columwise

np.mean(arr,axis=1)   # row-wise

array([2., 5., 8.])

In [37]:
np.median(arr)

np.float64(5.0)

In [38]:
arr = np.array([1,2,3,4,5])
arr
arr.cumsum()
arr.cumprod()
np.clip(arr, 2, 4)

array([2, 2, 3, 4, 4])

In [39]:
# rounding functions

a = np.array([1.2, 2.5, 3.7, 4.1, 5.9])
a
np.round(a)

array([1., 2., 4., 4., 6.])

In [40]:
# floor

np.floor(a)             #down
np.ceil(a)              # up

array([2., 3., 4., 5., 6.])

In [41]:
# trunc

np.trunc(a)             # towards zero

array([1., 2., 3., 4., 5.])

In [42]:
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(10, 20, (2, 3))
a
b
np.vstack((a, b))
np.hstack((a, b))
np.stack((a, b), axis=1)
np.stack((a, b), axis=0)


array([[[ 8,  5,  3],
        [ 1,  7,  9]],

       [[12, 14, 16],
        [17, 11, 18]]], dtype=int32)

In [43]:
# 3d array

arr = np.random.randint(1, 10, (2, 4, 4))              # depth , row, column     
arr


array([[[6, 7, 8, 2],
        [2, 7, 5, 9],
        [1, 5, 3, 2],
        [4, 9, 3, 9]],

       [[1, 7, 7, 1],
        [1, 2, 9, 9],
        [6, 3, 8, 3],
        [2, 7, 5, 5]]], dtype=int32)

In [44]:

arr = np.random.randint(1, 10, (4, 4))
arr

array([[7, 7, 1, 9],
       [8, 4, 6, 3],
       [8, 2, 2, 2],
       [4, 7, 6, 5]], dtype=int32)

In [45]:
# 3d array reshape
arr = np.arange(1, 21).reshape(2, 2, 5)
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [ ]:
b = np.random.randint(10, 20, (2, 3))


array([[13, 13, 16],
       [16, 17, 11]], dtype=int32)

In [48]:
# matrix multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # dot product
print(a @ b)  # using @ operator for dot product
print(np.matmul(a, b))  # using matmul function for dot product

32
32
32


In [52]:

a = np.random.randint(1, 10, (3, 3))
a
np.sort(a)            # row wise sorting
np.sort(a , axis=0)      # column wise sorting

array([[4, 2, 2],
       [5, 6, 5],
       [6, 6, 5]], dtype=int32)

In [57]:
a = np.array([3, 1, 2, 5, 4])
np.argsort(a)


array([1, 2, 0, 4, 3])