In [7]:
import numpy as np

In [8]:
arr = np.arange(3, 61, 3)
print(arr)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]


In [9]:
arr = np.arange(3, 61, 3)
print(arr)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]


In [10]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [11]:
a = np.array([1, 2, 3])
b = np.array([[1, 2]])
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (1,2) 

In [ ]:
a = np.array([2, 3, 4])
b = np.array([1, 0, 1])

print(np.dot(a, b))

In [ ]:
arr = np.arange(10)
print(arr.reshape(3, 3))

In [ ]:
arr = np.eye(5)
print(arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
view = arr[1:4]
view[0] = 99
print(arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
view = arr[1:4]
view[0] = 99
print(arr)

In [ ]:
marks = np.array([45, 78, 92, 34, 88, 55, 67])
print(marks[marks > 60])

In [ ]:
arr = np.random.randint(1, 101, 10)
print("Array:", arr)
print("Even numbers:", arr[arr % 2 == 0])

In [ ]:
print(np.array([1, "2", 3]).dtype)

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Row mean:", np.mean(arr, axis=1))
print("Column mean:", np.mean(arr, axis=0))

In [ ]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
flat[0] = 100
print(arr)

In [ ]:
degrees = np.array([0, 30, 45, 60, 90])

radians = np.deg2rad(degrees)
print("Radians:", radians)
print("Sine:", np.sin(radians))

In [ ]:
np.random.seed(10)
arr1 = np.random.randint(1, 51, 5)

np.random.seed(10)
arr2 = np.random.randint(1, 51, 5)

print(arr1)
print(arr2)
print(np.array_equal(arr1, arr2))

In [ ]:
arr = np.arange(12)
print(arr.reshape(2, -1).shape)

In [ ]:
arr = np.arange(1, 17).reshape(4, 4)
print(np.diagonal(arr))

In [ ]:
print(np.array([1, 2, 3]).shape)

In [ ]:
arr = np.array([[2, 0], [0, 3]])

values, vectors = np.linalg.eig(arr)

print("Eigenvalues:", values)
print("Eigenvectors:")
print(vectors)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix product:")
print(a @ b)

print("Element-wise multiplication:")
print(a * b)